version: '3.8'
services:

  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki && \
        mkdir -p /data/tempo && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_UPDATE=off
      - MINIO_CONSOLE_ADDRESS=:9001
    expose:
      - 9000
    ports:
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./configs/loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
    depends_on:
      - minio

  promtail:
    image: grafana/promtail:2.8.2
    command: -config.file=/etc/promtail/config.yml
    volumes:
      # custom config will read logs from the containers of this project
      - ./configs/promtail/config.yml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.1.1
    command: [ "-config.file=/etc/config.yml" ]
    volumes:
      - ./configs/tempo/config.yml:/etc/config.yml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9411:9411"  # zipkin http
    depends_on:
      - minio
      - prometheus

  prometheus:
    image: prom/prometheus:v2.44.0
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=2d
    volumes:
      - ./configs/prometheus/config.yml:/etc/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  # default credentials: admin/admin
  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    volumes:
      # automatically configure the loki datasource
      - ./configs/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana

  comment-service:
    build:
      context: comment-service/
    ports:
      - "8002:8002"
    labels:
      logging: "promtail"

  post-service:
    build:
      context: post-service/
    ports:
      - "8001:8001"
    labels:
      logging: "promtail"

volumes:
  minio-data:
  loki-data:
  tempo-data:
  prometheus-data:
  grafana-data: