#
# automatically configure the loki datasource in grafana
#
apiVersion: 1

datasources:

  # See https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-prometheus-data-source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    uid: prometheus
#    jsonData:
#      httpMethod: POST
#      exemplarTraceIdDestinations:
#        # Field with internal link pointing to data source in Grafana.
#        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
#        - datasourceUid: tempo
#          name: traceID

  # See https://grafana.com/docs/grafana/latest/datasources/tempo/#provision-the-tempo-data-source
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    uid: tempo
    jsonData:
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false

  # See https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
